// Code generated by lab.nexedi.com/kirr/go123/tracing/cmd/gotrace; DO NOT EDIT.

package server
// code generated for tracepoints

import (
	"lab.nexedi.com/kirr/neo/go/xcommon/tracing"
	_ "unsafe"

	"lab.nexedi.com/kirr/neo/go/neo"
)

// traceimport: "lab.nexedi.com/kirr/neo/go/neo"

// rerun "gotrace gen" if you see link failure ↓↓↓
//go:linkname neo_trace_exporthash lab.nexedi.com/kirr/neo/go/neo._trace_exporthash_bc56cd7a9caf82c14d9586243f763e65afb91ea0
func neo_trace_exporthash()
func init() { neo_trace_exporthash() }


//go:linkname neo_traceConnRecv_Attach lab.nexedi.com/kirr/neo/go/neo.traceConnRecv_Attach
func neo_traceConnRecv_Attach(*tracing.ProbeGroup, func(c *neo.Conn, msg neo.Msg)) *tracing.Probe

//go:linkname neo_traceConnSend_Attach lab.nexedi.com/kirr/neo/go/neo.traceConnSend_Attach
func neo_traceConnSend_Attach(*tracing.ProbeGroup, func(c *neo.Conn, msg neo.Msg)) *tracing.Probe
