#!/bin/sh
PYTHON=python2.6
INSTALL_DIR=eggs/

cd dirname $0/..
case "$1" in
  "develop")
  MODE=develop
  PYTHONPATH=$PYTHONPATH:$INSTALL_DIR;;
  *) MODE=bdist_egg ;;
esac

$PYTHON setup_client.py $MODE --dist-dir=$INSTALL_DIR
$PYTHON setup_common.py $MODE --dist-dir=$INSTALL_DIR
$PYTHON setup_admin.py $MODE --dist-dir=$INSTALL_DIR
$PYTHON setup_ctl.py $MODE --dist-dir=$INSTALL_DIR
$PYTHON setup_tests.py $MODE --dist-dir=$INSTALL_DIR
$PYTHON setup_storage.py $MODE --dist-dir=$INSTALL_DIR
$PYTHON setup_master.py $MODE --dist-dir=$INSTALL_DIR

