#! /usr/bin/env python
#
# neoadmin - run an administrator  node of NEO
#
# Copyright (C) 2009  Nexedi SA
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

from optparse import OptionParser
from neo.neoctl.app import Application
from neo import buildFormatString
import logging
parser = OptionParser()
parser.add_option('-v', '--verbose', action = 'store_true', 
                  help = 'print verbose messages')
parser.add_option('-p', '--port', help = 'specify the port of admin node',
                  type='int')
parser.add_option('-i', '--ip', help = 'specify the ip of admin node')
parser.add_option('--handler', help = 'specify the connection handler')

(options, args) = parser.parse_args()

port = options.port or 5555
ip = options.ip or '127.0.0.1'
handler = options.handler or "SocketConnector"

format = buildFormatString('neoctl')
if options.verbose:
    logging.basicConfig(level=logging.DEBUG, format=format)
else:
    logging.basicConfig(level=logging.INFO, format=format)
  
  
app = Application(ip, port, handler)
print app.execute(args)


